name: HTTP Request Action
on:
  push:
    branches: main
  fork:
    branches: main
  issues:
    types: [opened, closed]
    branches: main
  pull_request:
    types: [opened, closed]
    branches: main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Log payload
      run: echo fromJSON9${{ github.event }})
    - name: Contact DPR
      id: myRequest
      uses: fjogeleit/http-request-action@v1.8.1
      with:
        url: 'https://devprogramresourcesdev.service-now.com/api/x_snc_code_snippet/code_snippets/event'
        method: 'POST'
        contentType: application/json
        data: >
          {"title":"${{ github.event_name }} by ${{ github.actor }}",
          "username": "${{ github.actor }}",
          "event_name": "${{ github.event_name }}",
          "commit_sha": "${{ github.sha }}"}
        username: ${{ secrets.DPRD_USERNAME }}
        password: ${{ secrets.DPRD_PASSWORD }}
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
